### ISSUE TITLE
Korekta

### ISSUE THREAD

**Issue by masagrator** [bandithedoge/switch-pl#1]
Oto, co udało mi się wyłapać:
>Blokada ekranu
>>Po wybudzeniu konsoli z trybu uśpienia, wciśnij ten sam przycisk 3 razy aby użyć konsoli. -> przecinek przed aby

>Ochrona rodzicielska
>>Nintendo oferuje opcje stworzenia bezpiecznego środowiska dla dziecka używając blokady rodzicielskiej. -> przecinek przed "używając"

>Zarządzanie danymi
>>Zwalnia miejsce archiwizując wybrane aplikacje -> przecinek przed archiwizując

>Mii
>>Możesz stworzyć własnego Mii łącząc różne części twarzy i ciała aby użyć go w kompatybilnych aplikacjach. > przecinki przed łącząc i aby

>Wyjście wideo
>>Telewizor zostanie włączony kiedy konsola jest przełączona w tryb TV lub wybudzona ze stanu uśpienia w trybie TV. Wyłączenie telewizora spowoduje przejście konsoli w tryb uśpienia. -> przecinek przed kiedy

I według mnie niepotrzebnie przetłumaczyliście Pro Controller na kontroler Pro, ponieważ to nazwa własna (Japończycy zapisują to jako połączenie angielskiego Pro i japońskiego zapisu angielskiego controller).

**Comment by bandithedoge** [comment]
Dzięki! Zaraz to poprawię. Jeżeli chcesz, możesz edytować pliki w Kuriimu i zrobić pull requesta.
