### ISSUE TITLE
10.0.x missed a spot.

### ISSUE THREAD

**Issue by tomxhachijuroku** [bandithedoge/switch-pl#15]
Hej, thanks for your hard work, but the description under "Przenieś na pamięć wewnętrzną" is still in english, you may want to know that.

**Comment by bandithedoge** [comment]
Can you send a screenshot?

**Comment by tomxhachijuroku** [comment]
![obraz](https://user-images.githubusercontent.com/64981865/83801462-74f33080-a6a9-11ea-9db1-1a2763bb98df.png)
Here, the screenshot function was disabled so I made a photo, and as a "bonus" the system language still shows "English".
