### ISSUE TITLE
Poprawa paru nieprzetłumaczonych fragmentów

### ISSUE THREAD

**Issue by eHerbaciarz** [bandithedoge/switch-pl#20]
Wersja 1.5.1

Pomijając informacje błędów i i inne zgody użytkownika (o których wspominałeś, że ich nie przetłumaczyłeś) To znalazłem trzy (albo dwa w zależności od interpretacji) babole:

1) Ustawienia -> System -> Zoom - można by przetłumaczyć jako powiększenie. Jeżeli będzie poprawiana nazwa to także poprawić to w drugim miejscu (opis tej funkcji).

2) Ustawienia -> Tryb uśpienia -> Automatyczne uśpienie (tryb TV), ma jednostki "hr", w języku polskim powinniśmy użyć "godz."

3) Ustawienia -> Tryb uśpienia -> Automatyczne uśpienie (tryb TV) pomiędzy czasem a jednostką brakuje spacji (w przypadku 1 hr - jest dobrze, w pozostałych już nie)

4) Ustawienia -> Tryb uśpienia -> Automatyczne uśpienie (ekran konsoli), podobny błąd jak powyżej pomiędzy czasem a jednostką brakuje spacji (w przypadku 10 min - jest dobrze, w pozostałych już [nie)]

![20_1](https://user-images.githubusercontent.com/10764145/91043185-6dda1f80-e613-11ea-88e0-6fef0e2da54c.jpg)
![20_2](https://user-images.githubusercontent.com/10764145/91043186-6f0b4c80-e613-11ea-90ba-6ec2daddc6e3.jpg)
![20_4](https://user-images.githubusercontent.com/10764145/91043187-6fa3e300-e613-11ea-8123-68f9128a4637.jpg)

**Comment by bandithedoge** [comment]
Gdzie?

**Comment by bandithedoge** [comment]
Zoom raczej nie będzie tłumaczony, a resztę sprawdzimy przy następnej wersji.

**Comment by tomxhachijuroku** [comment]
Przecież Zoom został już przetłumaczony:
![obraz](https://user-images.githubusercontent.com/64981865/92465561-0903f500-f1cf-11ea-873f-a41e93abee7c.png)
Wystarczy że zrobisz tak:
![obraz](https://user-images.githubusercontent.com/64981865/92465669-2cc73b00-f1cf-11ea-8f51-032a673ea05b.png)
Co ty na to?

**Comment by tomxhachijuroku** [comment]
Hej, @etharos jeśli chodzi o hr i min to wszędzie nie ma spacji i powinno być tak:
![obraz](https://user-images.githubusercontent.com/64981865/92466172-00f88500-f1d0-11ea-8bc0-e90dc1220806.png)
