### ISSUE TITLE
Broken on Atmosphere 0.18.0

### ISSUE THREAD

**Issue by bandithedoge** [bandithedoge/switch-pl#23]
There must have been some breaking change in 0.18.0 that broke the translation. It was working fine on firmware 11.0.1 and a previous version of Atmosphere but now it completely crashes the system after updating to 0.18.0.
![photo_2021-02-13 10 38 07](https://user-images.githubusercontent.com/26331682/107846885-959e8900-6de7-11eb-858e-93af0229530f.jpeg)

**Comment by tomxhachijuroku** [comment]
Happened to me to, but it works on 0.18.1:
![2021041604430300-57B4628D2267231D57E0FC1078C0596D](https://user-images.githubusercontent.com/64981865/114964418-ffcabd00-9e6e-11eb-9041-99dab97d7c1d.jpg)
But I don't remember what I did exactly, I tried lots of things first I went back to 0.17.1 and uninstalled custom theme, and deleted:
"romfs_metadata.bin" file
"lyt" folder
From the "0100000000001000" folder, but I did all of that when updating to Atmosphere 0.18.1, so I'm not sure if any of that help, or just updating to 0.18.1 fixed the problem, so test if for yourself, good luck.
