### ISSUE TITLE
Nieprzetłumaczony błąd 

### ISSUE THREAD

**Issue by iGom** [bandithedoge/switch-pl#6]
Znalazłem nieprzetłumaczony błąd (FW 8.1.0)
![2020010419061900-1AB131B6E6571375B79964211BB3F5AE](https://user-images.githubusercontent.com/4786772/71771169-0a3d9d80-2f2f-11ea-8da2-014bd8a1ade7.jpg)

**Comment by bandithedoge** [comment]
Tego typu błędy nie mogą być przetłumaczone.
